### PR TITLE
Hello world from python and some changes in readme.md file

### PR DESCRIPTION
**Pull request by nishantkumar1308**

### CODE REVIEW

**Review by Vitaljaz — CHANGES_REQUESTED** [review]
Don't change README.md file, restore it

**Comment by nishantkumar1308** [comment]
Can u merge this to the main branch?

**Comment by Vitaljaz** [comment]
@nishantkumar1308 i think you need recreate branch and PR, because current branch is broken

**Comment by nishantkumar1308** [comment]
how can i recreate it can u tell me .I am beginner in it.

**Pull request closed without merging**
